### ISSUE TITLE
Update to Latest Version?

### ISSUE THREAD

**Issue by orecus** [Toilal/guessit-rest#16]
Hi,

Was looking into to why I got difference results from a local GuessIt parse and a GuessIt-Rest parse, noticed that the Rest API is outdated.

Can this be updated to the latest version please?

**Comment by Toilal** [comment]
I have update the docker image on docker hub. The testing API is coming back soon.

**Comment by Toilal** [comment]
It's back on http://api.guessit.io or https://api.guessit.io
